name: OpenJDK 11 Runtime Image CI
on: [push, pull_request]
env:
  LANG: en_US.UTF-8
  CEKIT_VERSION: 3.11.0
  S2I_URI: https://github.com/openshift/source-to-image/releases/download/v1.3.1/source-to-image-v1.3.1-a5a77147-linux-amd64.tar.gz
jobs:
  openjdkci:
    name: OpenJDK Runtime Build and Test
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Verify latest UBI image is present
        run: |
          docker pull registry.access.redhat.com/ubi8/ubi-minimal:latest
          docker image ls | grep ubi8
      - name: Setup required system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y krb5-multidev virtualenv
      - name: Setup virtualenv and install cekit and required packages
        run: |
          mkdir ~/cekit${{ env.CEKIT_VERSION }}
          virtualenv -p python3.6 ~/cekit${{ env.CEKIT_VERSION }}
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          pip3 install cekit==${{ env.CEKIT_VERSION }} docker docker-squash odcs behave lxml
      - name: Build
        run: |
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          cekit -v --descriptor ubi8-openjdk-11-runtime.yaml build docker
          docker image ls
      - name: Behave Tests
        run: |
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          cekit -v --descriptor ubi8-openjdk-11-runtime.yaml test behave
