name: UBI9 OpenJDK 17 Runtime S2I Image CI
on: [push, pull_request]
env:
  LANG: en_US.UTF-8
  IMAGE: ubi9-openjdk-17-runtime
jobs:
  openjdkci:
    name: OpenJDK S2I Build and Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Verify latest UBI image is present
        run:  docker pull registry.access.redhat.com/ubi9/ubi-minimal:latest

      - name: Install CEKit
        uses: cekit/actions-setup-cekit@v1.1.5

      - name: Build
        run: |
          cekit -v --descriptor ${{ env.IMAGE }}.yaml build docker

      - name: Install and cache S2I CLI tool from GitHub
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "github"
          github_pat: ${{ github.token }}
          s2i: "1.3.6"

      - name: Behave Tests
        run: |
          echo /home/runner/work/_temp/openshift-bin >> $GITHUB_PATH
          cekit -v --descriptor ${{ env.IMAGE }}.yaml test behave
